[package]
name = "rmqhgen"
description = "Generate and validate RabbitMQ password hashes"
version = "0.2.4"
authors = ["Guillaume Charmetant <cguille.dev@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "*"
clap = "*"
rand = "*"
rust-crypto = "*"
