name: Test

on:
  workflow_dispatch: ~
  push: ~
  pull_request: ~
  schedule:
    - cron: "45 6 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Rust toolchain versions
        run: rustc -Vv && cargo -Vv
      - uses: actions/checkout@v3
      - name: Cargo tests
        run: cargo test --verbose
